using System.Collections.Generic;

namespace CurioClerk.Localization
{
    public sealed class Localizer
    {
        private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
        {
            ["title"] = "CURIO CLERK",
            ["subtitle"] = "NIGHT SHIFT",
            ["start"] = "Start Shift",
            ["daily"] = "Daily File",
            ["daily_available"] = "Available",
            ["daily_completed"] = "Completed · Best {0}",
            ["daily_badge"] = "DAILY FILE · {0}",
            ["daily_result_best"] = "Today's best: {0}",
            ["collection"] = "Casebook",
            ["settings"] = "Settings",
            ["tutorial_title"] = "Three desks. One rulebook.",
            ["tutorial_body"] = "Clock in, then learn the three desks by sorting six curios.",
            ["tutorial_controls"] = "REPAIR · STORAGE · VAULT\nUse HOLD when you need a second look.",
            ["tutorial_goal"] = "Each docket needs one REPAIR, one STORAGE, and one VAULT stamp.",
            ["tutorial_first_docket_complete"] = "One docket complete! You used each desk once.",
            ["tutorial_finish"] = "Fill all three stamps. If a curio's desk is already full, Hold it.",
            ["tutorial_step_first_vault"] = "1 / 7 · CURSED goes to VAULT. File the key.",
            ["tutorial_step_hold"] = "2 / 7 · VAULT is already stamped. HOLD the shadow.",
            ["tutorial_step_first_repair"] = "3 / 7 · Fill the missing REPAIR stamp.",
            ["tutorial_step_first_storage"] = "4 / 7 · STORAGE closes the first docket.",
            ["tutorial_step_second_storage"] = "5 / 7 · Begin the next docket with STORAGE.",
            ["tutorial_step_second_repair"] = "6 / 7 · Add REPAIR. The held shadow will return.",
            ["tutorial_step_final_vault"] = "7 / 7 · File the returned shadow to VAULT.",
            ["tutorial_blocked"] = "That desk is already stamped. Use HOLD to reach a missing desk.",
            ["tutorial_follow_step"] = "FOLLOW THE NOTE · Complete the current lesson first.",
            ["tutorial_complete_title"] = "Training Complete",
            ["tutorial_complete_body"] = "The rulebook is yours. Your first full night shift is ready.",
            ["tutorial_start_shift"] = "Start First Shift",
            ["begin"] = "Clock In",
            ["repair"] = "REPAIR",
            ["storage"] = "STORAGE",
            ["vault"] = "VAULT",
            ["hold"] = "HOLD",
            ["hold_for_next"] = "HOLD FOR NEXT DOCKET",
            ["next"] = "NEXT",
            ["rules"] = "TONIGHT'S RULES",
            ["fallback"] = "Otherwise → Storage",
            ["correct"] = "Filed neatly.",
            ["wrong"] = "Wrong desk. Correct: {0}",
            ["decision_prompt"] = "Compare its traits with tonight's rules.",
            ["hold_required"] = "The correct desk is {0}, but it is already full. Hold this curio.",
            ["shift_hud"] = "HEARTS {0}   DOCKET {1}/{2}   CLEAN {3}   COINS {4}",
            ["docket"] = "DOCKET",
            ["docket_empty"] = "EMPTY",
            ["docket_complete"] = "COMPLETE",
            ["docket_complete_feedback"] = "DOCKET COMPLETE · +{0}",
            ["docket_pristine_feedback"] = "PRISTINE STREAK {0}",
            ["blocked"] = "That desk is already stamped. Use HOLD.",
            ["docket_pristine"] = "PRISTINE",
            ["docket_inked"] = "INKED",
            ["rule_reason"] = "{0} -> {1}",
            ["rule_priority_reason"] = "{0} took priority -> {1}",
            ["fallback_reason"] = "No special rule -> {0}",
            ["result_dockets"] = "NIGHT LEDGER",
            ["result_waiting"] = "The remaining curios wait beneath a blanket for the next night clerk.",
            ["resolution_label"] = "AFTER FILING",
            ["feedback_correct_label"] = "CORRECT",
            ["feedback_wrong_label"] = "WRONG",
            ["result_correct_label"] = "CORRECT",
            ["result_mistakes_label"] = "MISTAKES",
            ["complete"] = "Shift Complete",
            ["failed"] = "Office Closed Early",
            ["continue"] = "Return to Desk",
            ["revive"] = "Watch ad: restore 1 heart",
            ["double"] = "Watch ad: double base coins",
            ["ad_unavailable"] = "Rewarded ad unavailable",
            ["ad_dismissed"] = "Ad dismissed. No changes were made.",
            ["ad_failed"] = "Ad failed. No changes were made.",
            ["coins"] = "Coins",
            ["score"] = "Score",
            ["back"] = "Back",
            ["language"] = "Language",
            ["feedback_settings"] = "Feedback",
            ["sound"] = "Sound",
            ["haptics"] = "Haptics",
            ["on"] = "On",
            ["off"] = "Off",
            ["privacy"] = "Privacy",
            ["casebook_empty"] = "Correctly sort curios to reveal their case files.",
            ["casebook_tab"] = "CASEBOOK",
            ["casebook_discovered"] = "{0} / {1} DISCOVERED",
            ["casebook_locked"] = "LOCKED CASE FILE",
            ["cosmetics"] = "DESK CHARMS",
            ["cosmetics_tab"] = "DESK CHARMS",
            ["collection_coins"] = "COINS {0}",
            ["cosmetic_unlock_status"] = "UNLOCK · {0} COINS",
            ["cosmetic_equip_status"] = "EQUIP",
            ["cosmetic_equipped_status"] = "EQUIPPED",
            ["cosmetic_equipped_feedback"] = "{0} equipped",
            ["owned"] = "Owned",
            ["equip"] = "Equip",
            ["equipped"] = "Equipped",
            ["insufficient"] = "Not enough coins",
            ["unlock"] = "Unlock {0} coins",
            ["privacy_options"] = "Ad privacy options",
            ["incident_begin"] = "Begin Incident",
            ["incident_continue"] = "Continue Incident · {0}/5",
            ["incident_stage"] = "Incident {0}/5",
            ["incident_complete"] = "First Incident Resolved",
            ["incident_replay"] = "Replay Incident",
            ["incident_next_teaser"] = "Next Incident · The Umbrella That Rained Indoors",
            ["free_shift"] = "Free Shift",
            ["senior_clerk"] = "Senior Clerk",
            ["narrative_continue"] = "Continue",
            ["retry_stage"] = "Retry This Shift",
            ["next_stage"] = "Next Shift",
            ["quality_stable"] = "Stable",
            ["quality_precise"] = "Precise",
            ["quality_resonant"] = "Resonant",
            ["quality_stable_body"] = "The shift recovered. The incident remains safely contained.",
            ["quality_precise_body"] = "Calm care kept every seal intact.",
            ["quality_resonant_body"] = "Your care made the curio answer.",
            ["trait_frosted"] = "FROSTED",
            ["calm_streak"] = "Your hands have steadied.",
            ["incident_hold_protect"] = "PROTECT IN HOLD",
            ["incident_failed_body"] = "The office is still here. Try the same shift again when you are ready.",
            ["trait_cursed"] = "CURSED",
            ["trait_fragile"] = "FRAGILE",
            ["trait_alive"] = "ALIVE",
            ["trait_temporal"] = "TEMPORAL",
            ["trait_wet"] = "WET",
            ["trait_metallic"] = "METALLIC"
        };

        private static readonly IReadOnlyDictionary<string, string> Korean = new Dictionary<string, string>
        {
            ["title"] = "기묘한 분실물",
            ["subtitle"] = "야간반",
            ["start"] = "교대 시작",
            ["daily"] = "오늘의 서류",
            ["daily_available"] = "도전 가능",
            ["daily_completed"] = "완료 · 최고 {0}",
            ["daily_badge"] = "오늘의 서류 · {0}",
            ["daily_result_best"] = "오늘의 최고 점수: {0}",
            ["collection"] = "수집 도감",
            ["settings"] = "설정",
            ["tutorial_title"] = "세 곳의 보관처, 한 권의 규칙표",
            ["tutorial_body"] = "출근해서 여섯 물건을 분류하며 세 장소를 배워보세요.",
            ["tutorial_controls"] = "수리실 · 보관실 · 봉인고\n헷갈리는 물건은 보류할 수 있습니다.",
            ["tutorial_goal"] = "장부 하나에는 수리실·보관실·봉인고 도장이 하나씩 필요해요.",
            ["tutorial_first_docket_complete"] = "장부 하나 완성! 세 장소를 한 번씩 사용했습니다.",
            ["tutorial_finish"] = "세 도장을 채우고, 자리가 찬 물건은 보류하세요.",
            ["tutorial_step_first_vault"] = "1 / 7 · 저주받음은 봉인고입니다. 열쇠를 분류하세요.",
            ["tutorial_step_hold"] = "2 / 7 · 봉인고 도장은 이미 찍혔습니다. 그림자를 보류하세요.",
            ["tutorial_step_first_repair"] = "3 / 7 · 비어 있는 수리실 도장을 채우세요.",
            ["tutorial_step_first_storage"] = "4 / 7 · 보관실 도장으로 첫 장부를 닫으세요.",
            ["tutorial_step_second_storage"] = "5 / 7 · 다음 장부를 보관실부터 시작하세요.",
            ["tutorial_step_second_repair"] = "6 / 7 · 수리실을 채우면 보류한 그림자가 돌아옵니다.",
            ["tutorial_step_final_vault"] = "7 / 7 · 돌아온 그림자를 봉인고에 분류하세요.",
            ["tutorial_blocked"] = "이미 찍힌 도장입니다. 보류해서 비어 있는 목적지를 찾으세요.",
            ["tutorial_follow_step"] = "안내 확인 · 현재 단계를 먼저 완료하세요.",
            ["tutorial_complete_title"] = "교육 완료",
            ["tutorial_complete_body"] = "이제 규칙표를 맡을 준비가 됐습니다. 첫 정식 교대를 시작하세요.",
            ["tutorial_start_shift"] = "첫 교대 시작",
            ["begin"] = "출근하기",
            ["repair"] = "수리실",
            ["storage"] = "보관실",
            ["vault"] = "봉인고",
            ["hold"] = "보류",
            ["hold_for_next"] = "다음 장부까지 보류",
            ["next"] = "다음",
            ["rules"] = "오늘 밤의 규칙",
            ["fallback"] = "그 외 → 보관실",
            ["correct"] = "깔끔하게 처리했습니다.",
            ["wrong"] = "잘못 분류했습니다. 정답: {0}",
            ["decision_prompt"] = "물건의 특성과 오늘 밤의 규칙을 비교하세요.",
            ["hold_required"] = "정답은 {0}이지만 이미 찼어요. 이 물건을 보류하세요.",
            ["shift_hud"] = "하트 {0}   장부 {1}/{2}   말끔 {3}   코인 {4}",
            ["docket"] = "장부",
            ["docket_empty"] = "빈칸",
            ["docket_complete"] = "완료",
            ["docket_complete_feedback"] = "장부 완성 · +{0}",
            ["docket_pristine_feedback"] = "완벽 장부 연속 {0}",
            ["blocked"] = "이미 찍힌 도장입니다. 보류를 사용하세요.",
            ["docket_pristine"] = "말끔함",
            ["docket_inked"] = "번짐",
            ["rule_reason"] = "{0} -> {1}",
            ["rule_priority_reason"] = "{0} 우선 -> {1}",
            ["fallback_reason"] = "특수 규칙 없음 -> {0}",
            ["result_dockets"] = "야간 장부",
            ["result_waiting"] = "남은 유물은 담요 아래에서 다음 야간반을 기다립니다.",
            ["resolution_label"] = "처리 후",
            ["feedback_correct_label"] = "정답",
            ["feedback_wrong_label"] = "오답",
            ["result_correct_label"] = "정답",
            ["result_mistakes_label"] = "실수",
            ["complete"] = "교대 완료",
            ["failed"] = "조기 폐점",
            ["continue"] = "책상으로 돌아가기",
            ["revive"] = "광고 시청: 하트 1개 회복",
            ["double"] = "광고 시청: 기본 코인 2배",
            ["ad_unavailable"] = "현재 보상형 광고를 이용할 수 없습니다",
            ["ad_dismissed"] = "광고가 닫혔습니다. 변경된 내용이 없습니다.",
            ["ad_failed"] = "광고를 재생하지 못했습니다. 변경된 내용이 없습니다.",
            ["coins"] = "코인",
            ["score"] = "점수",
            ["back"] = "뒤로",
            ["language"] = "언어",
            ["feedback_settings"] = "게임 반응",
            ["sound"] = "소리",
            ["haptics"] = "진동",
            ["on"] = "켜짐",
            ["off"] = "꺼짐",
            ["privacy"] = "개인정보",
            ["casebook_empty"] = "기물을 올바르게 분류하면 기록이 공개됩니다.",
            ["casebook_tab"] = "수집 도감",
            ["casebook_discovered"] = "{0} / {1} 발견",
            ["casebook_locked"] = "잠긴 기록",
            ["cosmetics"] = "책상 장식",
            ["cosmetics_tab"] = "책상 장식",
            ["collection_coins"] = "코인 {0}",
            ["cosmetic_unlock_status"] = "해금 · {0} 코인",
            ["cosmetic_equip_status"] = "장착",
            ["cosmetic_equipped_status"] = "장착 중",
            ["cosmetic_equipped_feedback"] = "{0} 장착 완료",
            ["owned"] = "보유 중",
            ["equip"] = "장착",
            ["equipped"] = "장착 중",
            ["insufficient"] = "코인이 부족합니다",
            ["unlock"] = "{0} 코인으로 해금",
            ["privacy_options"] = "광고 개인정보 설정",
            ["incident_begin"] = "사건 시작",
            ["incident_continue"] = "사건 계속 · {0}/5",
            ["incident_stage"] = "사건 {0}/5",
            ["incident_complete"] = "첫 사건 해결",
            ["incident_replay"] = "사건 다시보기",
            ["incident_next_teaser"] = "다음 사건 · 실내에서 비를 맞은 우산",
            ["free_shift"] = "자유 교대",
            ["senior_clerk"] = "선임 관리인",
            ["narrative_continue"] = "계속",
            ["retry_stage"] = "같은 교대 다시 하기",
            ["next_stage"] = "다음 교대",
            ["quality_stable"] = "안정",
            ["quality_precise"] = "정교",
            ["quality_resonant"] = "공명",
            ["quality_stable_body"] = "실수를 바로잡았습니다. 사건은 안전하게 진정되었습니다.",
            ["quality_precise_body"] = "침착한 손길로 모든 인장을 지켰습니다.",
            ["quality_resonant_body"] = "당신의 손길에 물건이 답했습니다.",
            ["trait_frosted"] = "서리 묻음",
            ["calm_streak"] = "손길이 안정되었습니다",
            ["incident_hold_protect"] = "보호 보류",
            ["incident_failed_body"] = "보관소는 그대로입니다. 준비되면 같은 교대를 다시 시작하세요.",
            ["trait_cursed"] = "저주받음",
            ["trait_fragile"] = "깨지기 쉬움",
            ["trait_alive"] = "살아 있음",
            ["trait_temporal"] = "시간성",
            ["trait_wet"] = "젖어 있음",
            ["trait_metallic"] = "금속성"
        };

        public Localizer(string locale)
        {
            Locale = locale == "ko" ? "ko" : "en";
        }

        public string Locale { get; private set; }

        public void SetLocale(string locale)
        {
            Locale = locale == "ko" ? "ko" : "en";
        }

        public string Get(string key, params object[] arguments)
        {
            var table = Locale == "ko" ? Korean : English;
            var value = table.TryGetValue(key, out var localized) ? localized : key;
            return arguments == null || arguments.Length == 0 ? value : string.Format(value, arguments);
        }

        public static IEnumerable<KeyValuePair<string, string>> Entries(string locale)
            => locale == "ko" ? Korean : English;
    }
}
